CREATE DATABASE familyfitgym;

USE familyfitgym;

CREATE TABLE PLANES (
	IdPlan INT NOT NULL,
	NombrePlan VARCHAR(60) NOT NULL,
	DuracionDias INT NOT NULL,
	Costo DECIMAL(10,2) NOT NULL,
	Descripcion VARCHAR(200),
	CONSTRAINT PK_PLANES PRIMARY KEY (IdPlan)
);

CREATE TABLE METODOPAGO (
	IdMetodoPago VARCHAR(20) NOT NULL,
	NombreMetodo VARCHAR(50) NOT NULL,
	EstadoActivo BIT NOT NULL,
	CONSTRAINT PK_METODOPAGO PRIMARY KEY (IdMetodoPago)
);

CREATE TABLE EVENTOS (
	IdEvento INT NOT NULL,
	NombreEvento VARCHAR(100) NOT NULL,
	Descripcion VARCHAR(200) NULL,
	CONSTRAINT PK_EVENTOS PRIMARY KEY (IdEvento)
);

CREATE TABLE PERSONA (
	NumDocumento VARCHAR(20) NOT NULL, 
	Nombres VARCHAR(100) NOT NULL,
	Apellidos VARCHAR(100) NOT NULL,
	PasswordHass VARCHAR(60) NOT NULL,
	FechaRegistro DATE NOT NULL, 
    Celular VARCHAR(20), 
    Correo VARCHAR(100), 
	CONSTRAINT PK_PERSONA PRIMARY KEY (NumDocumento)
);

CREATE TABLE SOCIO (
	NumDocumento VARCHAR(20) NOT NULL,
	CONSTRAINT PK_SOCIO PRIMARY KEY (NumDocumento),
	CONSTRAINT FK_PERSONA_SOCIO FOREIGN KEY (NumDocumento) 
		REFERENCES PERSONA (NumDocumento)
);

CREATE TABLE EMPLEADO (
	NumDocumento VARCHAR(20) NOT NULL,
	TipoEmpleado VARCHAR(20) NOT NULL,
	CONSTRAINT PK_EMPLEADO PRIMARY KEY (NumDocumento),
	CONSTRAINT FK_PERSONA_EMPLEADO FOREIGN KEY (NumDocumento) 
		REFERENCES PERSONA (NumDocumento)
);

CREATE TABLE MEMBRESIA (
	IdMembresia INT NOT NULL,
	FechaInicio DATE NOT NULL,
	FechaFin DATE NOT NULL,
	Estado VARCHAR(50) NOT NULL,
	NumDocumento VARCHAR(20), 
	IdPlan INT,
	CONSTRAINT PK_MEMBRESIA PRIMARY KEY (IdMembresia),
	CONSTRAINT FK_SOCIO_MEMBRESIA 
		FOREIGN KEY (NumDocumento) REFERENCES SOCIO (NumDocumento),
	CONSTRAINT FK_PLANES_MEMBRESIA 
		FOREIGN KEY (IdPlan) REFERENCES PLANES (IdPlan)
);

CREATE TABLE PAGO (
	IdPago INT NOT NULL,
	FechaPago DATETIME NOT NULL,
	Monto DECIMAL(10,2) NOT NULL,
	NumDocumento VARCHAR(20),
	IdMetodoPago VARCHAR(20),
	IdMembresia INT,
	CONSTRAINT PK_PAGO PRIMARY KEY (IdPago),
	CONSTRAINT FK_EMPLEADO_PAGO 
		FOREIGN KEY (NumDocumento) REFERENCES EMPLEADO (NumDocumento),
	CONSTRAINT FK_METODOPAGO_PAGO 
		FOREIGN KEY (IdMetodoPago) REFERENCES METODOPAGO (IdMetodoPago),
	CONSTRAINT FK_MEMBRESIA_PAGO 
		FOREIGN KEY (IdMembresia) REFERENCES MEMBRESIA (IdMembresia)
);

CREATE TABLE ASISTENCIA (
	IdAsistencia INT NOT NULL,
	NumDocumento VARCHAR(20) NOT NULL,
	FechaHoraEntrada DATETIME NOT NULL,
	CONSTRAINT PK_ASISTENCIA PRIMARY KEY (IdAsistencia, NumDocumento),
	CONSTRAINT FK_SOCIO_ASISTENCIA 
		FOREIGN KEY (NumDocumento) REFERENCES SOCIO (NumDocumento)
);

CREATE TABLE PROGRAMACION (
	IdProgramacion INT NOT NULL,
	LugarEvento VARCHAR(100) NOT NULL,
	FechaHoraEvento DATETIME NOT NULL,
	NumDocumento VARCHAR(20), 
	IdEvento INT, 
	CONSTRAINT PK_PROGRAMACION PRIMARY KEY (IdProgramacion),
	CONSTRAINT FK_EMPLEADO_PROGRAMACION 
		FOREIGN KEY (NumDocumento) REFERENCES EMPLEADO (NumDocumento), 
	CONSTRAINT FK_EVENTOS_PROGRAMACION 
		FOREIGN KEY (IdEvento) REFERENCES EVENTOS (IdEvento)
);

CREATE TABLE RESERVA (
	IdProgramacion INT NOT NULL,
	NumDocumento VARCHAR(20) NOT NULL,
	FechaHoraReserva DATETIME NOT NULL,
	CONSTRAINT PK_RESERVA PRIMARY KEY (IdProgramacion, NumDocumento),
	CONSTRAINT FK_PROGRAMACION_RESERVA 
		FOREIGN KEY (IdProgramacion) REFERENCES PROGRAMACION (IdProgramacion),
	CONSTRAINT FK_SOCIO_RESERVA 
		FOREIGN KEY (NumDocumento) REFERENCES SOCIO (NumDocumento)
);

CREATE TABLE ASISTENCIAEVENTO (
	IdProgramacion INT NOT NULL,
	NumDocumento VARCHAR(20) NOT NULL,
	FechaHoraAsis DATETIME NOT NULL,
	CONSTRAINT PK_ASISTENCIAEVENTO PRIMARY KEY (IdProgramacion, NumDocumento),
	CONSTRAINT FK_RESERVA_ASISTENCIAEVENTO 
		FOREIGN KEY (IdProgramacion, NumDocumento) REFERENCES RESERVA (IdProgramacion, NumDocumento)
);